const path = require('path')
const { CleanWebpackPlugin } = require('clean-webpack-plugin')
const nodeExternals = require('webpack-node-externals')
const MiniCss = require('mini-css-extract-plugin')
const copyPlugin = require('copy-webpack-plugin')

module.exports = {
  entry: './src/main.ts',
  externals: [nodeExternals()],
  output: {
    filename: 'index.js',
    path: path.resolve(__dirname, 'dist'),
    library: 'matterial',
    libraryTarget: 'umd',
    globalObject: 'this',
  },
  plugins: [
    new CleanWebpackPlugin(),
    new MiniCss({
      filename: '[name].css',
      chunkFilename: '[id].css',
    }),
    new copyPlugin({
      patterns: [{ from: 'src/styles', to: 'src/styles' }],
    }),
  ],
  module: {
    rules: [
      {
        test: /\.module\.scss$/,
        use: [
          { loader: MiniCss.loader },
          {
            loader: 'css-loader',
            options: {
              modules: {
                localIdentName: '[local]__[hash:base64:5]',
                // Local classes will be exported by name for use in components
                namedExport: true,
              },
              sourceMap: false,
            },
          },
          {
            loader: 'sass-loader',
            options: {
              // Prefer dart-sass
              implementation: require('sass'),
              sourceMap: false,
            },
          },
        ],
      },
      {
        test: /\.scss$/,
        exclude: /\.module\.scss$/,
        use: [
          { loader: MiniCss.loader },
          {
            loader: 'css-loader',
            options: {
              modules: false,
              sourceMap: false,
            },
          },
          {
            loader: 'sass-loader',
            options: {
              // Prefer dart-sass
              implementation: require('sass'),
              sourceMap: false,
            },
          },
        ],
      },
      {
        test: /\.tsx?$/,
        exclude: /node_modules/,
        use: ['ts-loader'],
      },
    ],
  },
  resolve: {
    // Identify all aliases generated by ts baseUrl
    alias: {
      components: path.resolve(__dirname, 'src/components/'),
      interfaces: path.resolve(__dirname, 'src/interfaces/'),
      lib: path.resolve(__dirname, 'src/lib/'),
      styles: path.resolve(__dirname, 'src/styles/'),
    },
    extensions: ['.tsx', '.ts', '.js', '.scss'],
  },
}
